export default IocalImage = {
  AstroSplash: require('../Icons/Images/AstroSplash.png'),
  Banner1: require('../Icons/Images/Banner1.png'),
  Heart: require('../Icons/Images/Heart.png'),
  Flower: require('../Icons/Images/Flower.png'),
  Chocolate: require('../Icons/Images/Chocolate.png'),
  MagicalBoll: require('../Icons/Images/MagicalBoll.png'),
  Crown: require('../Icons/Images/Crown.png'),
  Money: require('../Icons/Images/Money.png'),
  Subtract: require('../Icons/Images/Subtract.png'),
  Clock: require('../Icons/Images/Clock.png'),
  Taraju: require('../Icons/Images/Taraju.png'),
  Matchkundi: require('../Icons/Images/Matchkundi.png'),
  Ariea: require('../Icons/Images/Ariea.png'),
  Couple: require('../Icons/Images/OBJECTS.png'),
  Livechat: require('../Icons/Images/ChatBackgeound.png'),
  UserOne: require('../Icons/Images/User4.png'),
  UserTwo: require('../Icons/Images/User3.png'),
  WhitCross: require('../Icons/Images/WhitCross.png'),
  TwoUser: require('../Icons/Images/TwoUser.png'),
  SendMssg: require('../Icons/Images/SendMssg.png'),
  LightOrange: require('../Icons/Images/LightOrange.png'),
  DarkOrange: require('../Icons/Images/DarkOrange.png'),
  SkyBlue: require('../Icons/Images/SkyBlue.png'),

  // ---------- Footer icon ---------
  ActiveHome: require('../Icons/Images/ActiveHome.png'),
  DiativateHome: require('../Icons/Images/DiativateHome.png'),
  Activemessages: require('../Icons/Images/Activemessages.png'),
  Deactivemessage: require('../Icons/Images/Deactivemessage.png'),
  Play: require('../Icons/Images/Play.png'),
  Activecall: require('../Icons/Images/Activecall.png'),
  Deactivecall: require('../Icons/Images/Deactivecall.png'),
  Activepot: require('../Icons/Images/Activepot.png'),
  DeactivePlot: require('../Icons/Images/DeactivePlot.png'),
};
